# Generated by Django 6.0 on 2026-01-31 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('products', '0008_remove_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesaleinquiry',
            name='brand_interested',
        ),
        migrations.RemoveField(
            model_name='wholesaleinquiry',
            name='product_interested',
        ),
        migrations.AddField(
            model_name='wholesaleinquiry',
            name='brand_interested_old',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wholesale_brands_old', to='products.brand'),
        ),
        migrations.AddField(
            model_name='wholesaleinquiry',
            name='brands_interested',
            field=models.ManyToManyField(blank=True, related_name='wholesale_inquiries', to='products.brand'),
        ),
        migrations.AddField(
            model_name='wholesaleinquiry',
            name='product_interested_old',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wholesale_products_old', to='products.product'),
        ),
        migrations.AddField(
            model_name='wholesaleinquiry',
            name='products_interested',
            field=models.ManyToManyField(blank=True, related_name='wholesale_inquiries', to='products.product'),
        ),
    ]
