# Generated by Django 6.0 on 2026-01-31 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_migrate_old_wholesale_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesaleinquiry',
            name='brand_interested_old',
        ),
        migrations.RemoveField(
            model_name='wholesaleinquiry',
            name='product_interested_old',
        ),
    ]
