# Generated by Django 6.0 on 2025-12-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=200)),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('content', models.TextField(help_text='Main About Us text')),
                ('image', models.ImageField(blank=True, upload_to='pages/about/')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'About Page Configuration',
                'verbose_name_plural': 'About Page Configuration',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Welcome to TMR', max_length=200)),
                ('hero_image_1', models.ImageField(blank=True, upload_to='home/hero/')),
                ('hero_image_2', models.ImageField(blank=True, upload_to='home/hero/')),
                ('hero_image_3', models.ImageField(blank=True, upload_to='home/hero/')),
                ('hero_image_4', models.ImageField(blank=True, upload_to='home/hero/')),
                ('hero_image_5', models.ImageField(blank=True, upload_to='home/hero/')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Home Page Configuration',
                'verbose_name_plural': 'Home Page Configuration',
            },
        ),
    ]
