# Generated by Django 6.0 on 2026-01-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Internal title', max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, help_text='URL slug', null=True)),
                ('seo_title', models.CharField(blank=True, help_text='Browser tab title', max_length=200)),
                ('seo_description', models.TextField(blank=True, help_text='Meta description for search engines')),
                ('hero_title', models.CharField(blank=True, max_length=200)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, upload_to='pages/hero/')),
                ('content', models.TextField(blank=True, help_text='Main content (HTML/Text)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand Page Content (Generic)',
                'verbose_name_plural': 'Brand Page Content (Generic)',
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Internal title', max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, help_text='URL slug', null=True)),
                ('seo_title', models.CharField(blank=True, help_text='Browser tab title', max_length=200)),
                ('seo_description', models.TextField(blank=True, help_text='Meta description for search engines')),
                ('hero_title', models.CharField(blank=True, max_length=200)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, upload_to='pages/hero/')),
                ('content', models.TextField(blank=True, help_text='Main content (HTML/Text)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('map_embed_url', models.TextField(blank=True, help_text='Google Maps Embed URL')),
            ],
            options={
                'verbose_name': 'Contact Page Content',
                'verbose_name_plural': 'Contact Page Content',
            },
        ),
        migrations.CreateModel(
            name='WholesalePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Internal title', max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, help_text='URL slug', null=True)),
                ('seo_title', models.CharField(blank=True, help_text='Browser tab title', max_length=200)),
                ('seo_description', models.TextField(blank=True, help_text='Meta description for search engines')),
                ('hero_title', models.CharField(blank=True, max_length=200)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, upload_to='pages/hero/')),
                ('content', models.TextField(blank=True, help_text='Main content (HTML/Text)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wholesale Page Content',
                'verbose_name_plural': 'Wholesale Page Content',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'About Page Content', 'verbose_name_plural': 'About Page Content'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page Content', 'verbose_name_plural': 'Home Page Content'},
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='vision',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_image_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_image_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_image_3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_image_4',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_image_5',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='pages/hero/'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Meta description for search engines'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Browser tab title', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL slug', null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_section_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_section_title',
            field=models.CharField(default='About Us', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=models.TextField(blank=True, help_text='Main content (HTML/Text)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='pages/hero/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Meta description for search engines'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Browser tab title', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL slug', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title',
            field=models.CharField(blank=True, help_text='Internal title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='content',
            field=models.TextField(blank=True, help_text='Main content (HTML/Text)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='title',
            field=models.CharField(blank=True, help_text='Internal title', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='tiktok_url',
            field=models.URLField(blank=True, verbose_name='TikTok URL'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube URL'),
        ),
    ]
