# Generated by Django 6.0 on 2026-01-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_brandpagecontent_contactpage_wholesalepage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='slug',
            field=models.SlugField(default='default-slug', help_text='URL slug', unique=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='title',
            field=models.CharField(default='Default Title', help_text='Internal title', max_length=200),
        ),
        migrations.AlterField(
            model_name='brandpagecontent',
            name='slug',
            field=models.SlugField(default='default-slug', help_text='URL slug', unique=True),
        ),
        migrations.AlterField(
            model_name='brandpagecontent',
            name='title',
            field=models.CharField(default='Default Title', help_text='Internal title', max_length=200),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='slug',
            field=models.SlugField(default='default-slug', help_text='URL slug', unique=True),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='title',
            field=models.CharField(default='Default Title', help_text='Internal title', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slug',
            field=models.SlugField(default='default-slug', help_text='URL slug', unique=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title',
            field=models.CharField(default='Default Title', help_text='Internal title', max_length=200),
        ),
        migrations.AlterField(
            model_name='wholesalepage',
            name='slug',
            field=models.SlugField(default='default-slug', help_text='URL slug', unique=True),
        ),
        migrations.AlterField(
            model_name='wholesalepage',
            name='title',
            field=models.CharField(default='Default Title', help_text='Internal title', max_length=200),
        ),
    ]
