# Generated by Django 6.0 on 2026-01-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_aboutpage_slug_alter_aboutpage_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_image_1',
            field=models.ImageField(blank=True, upload_to='home/hero/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image_2',
            field=models.ImageField(blank=True, upload_to='home/hero/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image_3',
            field=models.ImageField(blank=True, upload_to='home/hero/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image_4',
            field=models.ImageField(blank=True, upload_to='home/hero/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image_5',
            field=models.ImageField(blank=True, upload_to='home/hero/'),
        ),
    ]
