# Generated by Django 6.0 on 2026-01-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_homepage_hero_image_1_homepage_hero_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='seo_keywords',
            field=models.TextField(blank=True, help_text='Meta keywords for search engines'),
        ),
        migrations.AddField(
            model_name='brandpagecontent',
            name='seo_keywords',
            field=models.TextField(blank=True, help_text='Meta keywords for search engines'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='seo_keywords',
            field=models.TextField(blank=True, help_text='Meta keywords for search engines'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_keywords',
            field=models.TextField(blank=True, help_text='Meta keywords for search engines'),
        ),
        migrations.AddField(
            model_name='wholesalepage',
            name='seo_keywords',
            field=models.TextField(blank=True, help_text='Meta keywords for search engines'),
        ),
    ]
