# Generated by Django 6.0 on 2026-01-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_aboutpage_seo_keywords_brandpagecontent_seo_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='clients_served_count',
            field=models.CharField(default='100+', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='expert_support_text',
            field=models.CharField(default='24/7 EXPERT SUPPORT', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='html_content',
            field=models.TextField(blank=True, help_text='Additional Detail Text (HTML/Text)'),
        ),
        migrations.AddField(
            model_name='brandpagecontent',
            name='html_content',
            field=models.TextField(blank=True, help_text='Additional Detail Text (HTML/Text)'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='html_content',
            field=models.TextField(blank=True, help_text='Additional Detail Text (HTML/Text)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='clients_served_count',
            field=models.CharField(default='100+', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='expert_support_text',
            field=models.CharField(default='24/7 EXPERT SUPPORT', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='html_content',
            field=models.TextField(blank=True, help_text='Additional Detail Text (HTML/Text)'),
        ),
        migrations.AddField(
            model_name='wholesalepage',
            name='html_content',
            field=models.TextField(blank=True, help_text='Additional Detail Text (HTML/Text)'),
        ),
    ]
