# Generated by Django 6.0 on 2026-01-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_aboutpage_clients_served_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='catalogue_file',
            field=models.FileField(blank=True, help_text='Upload the PDF catalogue', null=True, upload_to='catalogues/'),
        ),
    ]
