# Generated by Django 6.0 on 2026-01-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Meta keywords for search engines'),
        ),
    ]
