# Generated by Django 6.0 on 2026-01-31 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_meta_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_old', to='products.brand'),
        ),
    ]
