# Generated by Django 6.0 on 2026-01-31 08:51

from django.db import migrations

def copy_brand_to_brands(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    for product in Product.objects.all():
        if product.brand:
            product.brands.add(product.brand)

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_brands_alter_product_brand'),
    ]

    operations = [
        migrations.RunPython(copy_brand_to_brands, reverse_code=migrations.RunPython.noop),
    ]
