# Generated by Django 6.0 on 2026-01-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='content',
            field=models.TextField(blank=True, help_text='Main content (HTML/Text)'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='brands/hero/'),
        ),
        migrations.AddField(
            model_name='brand',
            name='hero_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='hero_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='brand',
            name='html_content',
            field=models.TextField(blank=True, help_text='Additional Detail Text (HTML/Text)'),
        ),
    ]
