# Generated by Django 6.0 on 2026-02-09 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.CreateModel(
            name='HomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Override category name for home page display', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Override category image for home page', null=True, upload_to='home_categories/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_display', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Home Categories',
                'ordering': ['order'],
            },
        ),
    ]
